### ISSUE TITLE
LaunchClamp1 not connected to the ground

### ISSUE THREAD

**Issue by neuPanda** [taniwha/Extraplanetary-Launchpads#112]
@PART[launchClamp1]:FOR[Launchpad]
{
    @MODULE[LaunchClamp] {
        @name = ExtendingLaunchClamp
    }
}

this code is busting the launch clamps on kerbin

![wtfksp](https://cloud.githubusercontent.com/assets/987235/12315941/ccae8ece-ba4e-11e5-9aa4-5f8fb9e87bc4.png)

**Comment by tedingus72** [comment]
I can confirm this issue is still in 5.3.  I am running KSP 1.1.0.1230(x64).  I removed all my mods and just added Module Manager 2.6.22 and EL 5.3.0 and I am having the same issue with the stock launch clamp.  The issue may either be in MM or the MM config for EL.  If I remove MM the Launch clamp issue does not appear.

**Comment by taniwha** [comment]
This should no longer be an issue as of KSP 1.2.
