### ISSUE TITLE
EL not loading 

### ISSUE THREAD

**Issue by Muteb512** [taniwha/Extraplanetary-Launchpads#160]
EL does not load any craft. in all launch pads 

I uploaded a video on youtube since photos won't be able to explain a thing.

[https://youtu.be/g2qFuuMPtd8](url)

**Comment by SteveBenz** [comment]
Can't watch the video to be certain, but I think I see the same thing.  Repro steps are pretty simple:

1.  Be running KSP 1.10.2917
2.  press the "Select Craft" button on the EL dialog
3. Choose any craft
4. Nothing happens, but that's because of this:

[EXC 23:41:38.430] NullReferenceException: Object reference not set to an instance of an object
	KSP.UI.Screens.CraftBrowserDialog.onPipelineFinished (ConfigNode n, KSP.UI.Screens.CraftEntry sItem, KSP.UI.Screens.CraftBrowserDialog+LoadType loadType) (at <c168e21ec56346b082f89043e76162e1>:0)
	KSP.UI.Screens.CraftBrowserDialog+<>c__DisplayClass126_0.<pipeSelectedItem>b__0 (ConfigNode n) (at <c168e21ec56346b082f89043e76162e1>:0)
	KSPUpgradePipeline.Process (ConfigNode n, System.String saveName, SaveUpgradePipeline.LoadContext loadContext, Callback`1[T] onSucceed, Callback`2[T,U] onFail) (at <c168e21ec56346b082f89043e76162e1>:0)
	KSP.UI.Screens.CraftBrowserDialog.pipeSelectedItem (KSP.UI.Screens.CraftEntry sItem, KSP.UI.Screens.CraftBrowserDialog+LoadType loadType) (at <c168e21ec56346b082f89043e76162e1>:0)
	KSP.UI.Screens.CraftBrowserDialog.ConfirmLoadCraft () (at <c168e21ec56346b082f89043e76162e1>:0)
	KSP.UI.Screens.CraftBrowserDialog.onButtonLoad () (at <c168e21ec56346b082f89043e76162e1>:0)
	UnityEngine.Events.InvokableCall.Invoke () (at <5aeafee3fea24f37abd1315553f2cfa6>:0)
	UnityEngine.Events.UnityEvent.Invoke () (at <5aeafee3fea24f37abd1315553f2cfa6>:0)
	UnityEngine.UI.Button.Press () (at <71b90c0cb66049febf95ce5efefd552e>:0)
	UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <71b90c0cb66049febf95ce5efefd552e>:0)
	UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <71b90c0cb66049febf95ce5efefd552e>:0)
	UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <71b90c0cb66049febf95ce5efefd552e>:0)
	UnityEngine.EventSystems.EventSystem:Update()
[LOG 23:41:42.635] [KSPUpgradePipeline]: Auto-Saved Ship (1.10.0) is up to date.

Might want to get with allista about this, because I saw the same reported against GroundConstruction

https://github.com/allista/GroundConstruction/issues/77

I see he closed the issue, and I assume he's found a work-around, but I don't see a commit associated with it.

**Comment by leonardfactory** [comment]
Seems that the `onPipelineFinished` signature has changed, now instead of `string filename` a `ConfigNode node` is provided. Relevant line in EL codebase is: https://github.com/taniwha/Extraplanetary-Launchpads/blob/ad848f9bd7eece4916f1fcc9ec7c82b528f58064/Source/GUI/BuildWindow.cs#L809 

While patch commit in GroundConstruction seems to be: https://github.com/allista/AT_Utils/commit/b31ea003c2e2690dbf0475b6f47e4524f6e80ac4

(See how the signature has been changed).

Not sure if this could be helpful. Anyway thank you @taniwha for your awesome job.

**Comment by taniwha** [comment]
This has been fixed and verified for 1.10.0 and 1.10.1. A release should be out soon.
