### ISSUE TITLE
Pads without a spawn transform sometimes explode.

### ISSUE THREAD

**Issue by taniwha** [taniwha/Extraplanetary-Launchpads#34]
Spawning ships on pads that do not have a spawn transform sometimes ends in the new ship colliding with the pad. Thanks to Seawolf for his efforts in narrowing this down.

I suspect the transform data is becoming stale due to the motion of the pad because the orbital dock, which has a spawn transform, has no problems spawning ships (for Seawolf).

**Comment by AtrumDeus** [comment]
I can confirm that both the LaunchPad2 part and the Runway part that came with EL will cause the root part of any ship spawned on them to be destroyed, and then will not release the build. Sometimes the release button DOES function, but the root part then explodes after. I have tested on both parts landed on Mun and Duna, and it is constant. These parts are useless for building on other planets. The survey stakes work nicely, though. Just have to make sure the ground is perfectly level where they are placed. 
At any rate, this bug was reproduced using 0.90 of KSP, and 5.0 of EL. Both parts cause the root part of anything built on them to be destroyed. I have even tried opening and closing the parts before spawning, but it still happens. No idea what a 'spawn transform' is, but this seems to be the correct bug. The orbital dock works as expected in orbit, have not tried it landed.

**Comment by taniwha** [comment]
Seems to have been fixed at some stage.
