### ISSUE TITLE
Can't build ships or access build menu for fully built space station

### ISSUE THREAD

**Issue by zicrog** [taniwha/Extraplanetary-Launchpads#44]
I probably should have addressed this before actually getting all the parts of my base to the mun ... but oh well ... anyways, I can't build anything ... I can open the pads ... but after that there is no launch option or anything ... no menu nothing

**Comment by carteralek** [comment]
I have been struggling with this issue as well.

The only two things I have installed are EL and Blizzys toolbar.
And still no option for a gui when i right click :(

**Comment by AviatorTrainman** [comment]
I had the same issue, I found that my antivirus had removed the KSPAPIExtensions.dll that came with the mod because it was infected, so I downloaded it from the forum thread and put it in the plugins folder. it now works fine. EPL version 5.2.1, KSP version 1.0.2. Hope this helps.
PS: You should probably fix the infected dll.

**Comment by Olympic1** [comment]
Even if a dll isn't infected, an antivirus can remove the dll if it isn't known in their database
